set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

unbind r
bind r source-file ~/.tmux.conf

set -g allow-rename off
set -g automatic-rename off
setw -g allow-rename off
setw -g automatic-rename off

set -g mouse on
#set -g default-terminal "tmux-256color"
set -g mode-keys vi
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-kitty:RGB"
set -g base-index 0
set -g renumber-windows on

set -g set-titles off

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g status-left ""
set -g status-left-length 100
set -g status-right-length 100

set -g status-right "#{E:@catppuccin_status_application}"
set -gaF status-right "#{@catppuccin_status_directory}"
set -ga status-right "#{E:@catppuccin_status_session}"

set -g status-interval 1

run '~/.tmux/plugins/tpm/tpm'
