#Font: clean + nerdy
font_family      0xProto Nerd Font
font_size        17
bold_font        auto
italic_font      auto
adjust_line_height 110%
adjust_column_width 102%

# Look & Feel
hide_window_decorations yes
window_border_width 0
window_padding_width 0  
confirm_os_window_close 0
cursor_shape beam
cursor_blink_interval 0
enable_audio_bell no

# Opacity & Blur (requires compositor)
background_opacity 0.92
background_blur 25

cursor                #ffffff
cursor_text_color     #6640FF
cursor_trail 100
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2 

foreground #795EFF
background #000000

# Performance
repaint_delay 3
input_delay 1
sync_to_monitor yes
