# BACKGROUND
background {
    monitor = eDP-1
    path = ~/Pictures/archgirl.png
    blur_passes = 0
    contrast = 1
    brightness = 1
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
    ignore_empty_input = true
}

# INPUT FIELD
input-field {
    monitor = eDP-1
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    rounding = -1
    placeholder_text = Password
    hide_input = false
    position = 0, -300
    halign = center
    valign = center
    check_color = rgb(108, 112, 134)
    fail_color = rgb(243, 139, 168)
    fail_text = Try again!
    fail_timeout = 2000
    fail_transition = 300
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgb(205, 214, 244)
    font_size = 22
    font_family = Firacode nerd Font
    position = -600, 300
    halign = center
    valign = center
}

# TIME
label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%-I:%M:%S"
    color = rgb(205, 214, 244)
    font_size = 120
    font_family = JetBrains Mono Extrabold
    position = -600, 400
    halign = center
    valign = center
}

label {
  text = cmd[update:10000] bash -c 'STATUS=$(cat /sys/class/power_supply/BAT0/status); \
  CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity); \
  if [ "$STATUS" = "Charging" ]; then \
    echo "Charging 󰂄 $CAPACITY%"; \
  else \
    echo "Battery   $CAPACITY%"; \
  fi'
  font_size = 18
  font_family = Firacode nerd Font
  position = 0, -500
  halign = center
  valign = center
}

