# --- Window Rules ---
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# --- Scratchpad Window Rules ---
windowrulev2 = workspace special:magic, class:^(scratchpad)$
windowrulev2 = float, class:^(scratchpad)$
windowrulev2 = size 1000 600, class:^(scratchpad)$
windowrulev2 = center, class:^(scratchpad)$

